# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Building Capitual
email: engineering@capitual.net
description: > # this means to ignore newlines until "baseurl:"
  Capitual Engineering Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://building.capitual.com" # the base hostname & protocol for your site
twitter_username: capitual
github_username:  capitual

permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown

authors:
  jesobreira:
    name: Jefrey S. Santos
    email: jefrey.santos@capitual.io
    twitter: https://twitter.com/jefreyssantos
    linkedin: https://linkedin.com/jesobreira
    github: https://github.com/jesobreira
    web: https://medium.com/jefreysantos
    bio: Full-stack developer and blockchain engineer. Disruptive technologies believer. CTO at Capitual.